name: "Farbfox/hetzner-cloud-deploy-server-action"
description: "Deploy a Hetzner Cloud Server from a GitHub Action"
author: "Tim Daubenschütz | Michael Schiller"
inputs:
  server-name:
    description: "The name your server should be initiated with."
    default: "gh-actions-ci-server"
    required: false
  server-type:
    description: "The Hetzner server type you want your server to be."
    required: true
  server-location:
    description: "The Hetzner server location (nbg1|...) you want your server to be."
    required: true
  image-identifier:
    description: "The name or ID of the Operating System image your server should be initiated with."
    required: true
  image-label:
    description: "The label of the Operating System image your server should be initiated with."
    required: false
  image-type:
    description: "The type (system|snapshot|backup|app) of the Operating System image your server should be initiated with."
    required: false
  ssh-key-name:
    description: "The ssh key, you want your server to be provisioned with."
    required: true
  hcloud-token:
    description: "Your Hetzner Cloud API token."
    required: true
  delete-server:
    description: "Regulates whether a server should be deleted after the action."
    required: false
    default: true
  startup-timeout:
    description: "Gives the server some time (in Milliseconds) to boot up before ending the action."
    required: false
    default: 40000
  floating-ip-id:
    description: "Allows to assign a floating IP to the server after deployment"
    required: false
  floating-ip-assignment-timeout:
    description: "Gives Hetzner some time (in Ms) to assign an IP to a server."
    required: false
    default: 60000

runs:
  using: "node12"
  main: "dist/deploy/index.js"
  post: "dist/clean/index.js"

branding:
  icon: server
  color: "yellow"
